steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - auto-deployed-function
  - --region=asia-south1
  - --source=.
  - --trigger-http
  - --runtime java 11